var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/favoris/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sy-36a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0opbbjh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wt485_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_0o9n36w._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_favoris_page_actions_0fq9j25.js")
R.m(88401)
module.exports=R.m(88401).exports
