var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/espace/itineraires/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1nmttwt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0opbbjh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wt485_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_espace_layout_tsx_06s9k7a._.js")
R.c("server/chunks/ssr/_next-internal_server_app_espace_itineraires_page_actions_18nb2ld.js")
R.m(12696)
module.exports=R.m(12696).exports
