// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(public)/billets/[reference]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billets/[reference]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/billets/[reference]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/connexion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connexion">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/connexion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/inscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inscription">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/inscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/mes-billets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mes-billets">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/mes-billets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/recherche/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recherche">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/recherche/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/reservation/[tripId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reservation/[tripId]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/reservation/[tripId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/compagnies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/compagnies">> = Specific
  const handler = {} as typeof import("../../src/app/espace/compagnies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/departs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/departs">> = Specific
  const handler = {} as typeof import("../../src/app/espace/departs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/embarquement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/embarquement">> = Specific
  const handler = {} as typeof import("../../src/app/espace/embarquement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/gares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/gares">> = Specific
  const handler = {} as typeof import("../../src/app/espace/gares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/guichet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/guichet">> = Specific
  const handler = {} as typeof import("../../src/app/espace/guichet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/itineraires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/itineraires">> = Specific
  const handler = {} as typeof import("../../src/app/espace/itineraires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/journal">> = Specific
  const handler = {} as typeof import("../../src/app/espace/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace">> = Specific
  const handler = {} as typeof import("../../src/app/espace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/profil">> = Specific
  const handler = {} as typeof import("../../src/app/espace/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/espace/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/utilisateurs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/utilisateurs">> = Specific
  const handler = {} as typeof import("../../src/app/espace/utilisateurs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/vehicules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/vehicules">> = Specific
  const handler = {} as typeof import("../../src/app/espace/vehicules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/villes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/espace/villes">> = Specific
  const handler = {} as typeof import("../../src/app/espace/villes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/espace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/espace">> = Specific
  const handler = {} as typeof import("../../src/app/espace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
