var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/reservation/[tripId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0go38a1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0opbbjh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wt485_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_1qtck4g._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_reservation_[tripId]_page_actions_16qlult.js")
R.m(48062)
module.exports=R.m(48062).exports
